services:
  - type: web
    name: web-rtc
    env: java
    buildCommand: mvn package -DskipTests
    startCommand: java -jar target/module-communication-1.0.0.jar
    envVars:
      - key: PORT
        value: 8080
